src/main/java/at/uda/multiplechoice/model/Student.java
package at.uda.multiplechoice.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;

@NamedQueries({
		@NamedQuery(name = "Student.findAll", query = "SELECT s FROM Student s WHERE s.archive = FALSE ORDER BY s.lastName,s.firstName"),
		@NamedQuery(name = "Student.findOrphans", query = "SELECT s FROM Student s WHERE NOT EXISTS (SELECT 1 FROM Classroom c WHERE c = s.classroom) AND s.archive = :param  ORDER BY s.lastName,s.firstName"),
		@NamedQuery(name = "Student.findStudentClassroom", query = "SELECT s FROM Student s WHERE s.classroom =:param AND s.archive = FALSE  ORDER BY s.lastName,s.firstName"),
		@NamedQuery(name = "Student.findStudentClassroomArchive", query = "SELECT s FROM Student s WHERE s.classroom =:param AND s.archive = TRUE  ORDER BY s.lastName,s.firstName"),
		@NamedQuery(name = "Student.findNoOrphan", query = "SELECT s FROM Student s  WHERE EXISTS (SELECT 1 FROM Classroom c WHERE c = s.classroom) AND s.archive = :param ORDER BY s.lastName,s.firstName") })
@DiscriminatorValue(value = "STUDENT")
@Entity
public class Student extends Person {
	public static final String findOrphans = "Student.findOrphans";
	public static final String findStudentsClassroom = "Student.findStudentClassroom";
	public static final String findNoOrphan = "Student.findNoOrphan";
	public static final String findStudentsClassroomArchive = "Student.findStudentClassroomArchive";

	@ManyToOne()
	private Classroom classroom;

	@OneToMany(mappedBy = "student", cascade = { CascadeType.ALL }, fetch = FetchType.LAZY, orphanRemoval = true)
	private List<Exam> exams = new ArrayList<>();

	public void addExam(Exam exam) {
		this.exams.add(exam);
		exam.setStudent(this);
	}

	public Classroom getClassroom() {
		return classroom;
	}

	public void setClassroom(Classroom classroom) {
		this.classroom = classroom;
	}

	public List<Exam> getExams() {
		return exams;
	}

	public void setExams(List<Exam> exams) {
		this.exams = exams;
	}
	@Override
	 public void removeForeignKeys() {
		this.classroom=null;
	}
	
	@Override
	public List<Exam> getChildren() {
		return exams;
	}
	
	@Override
	public <T extends AbstractEntity> void setParent(T entity) {
		classroom= (Classroom) entity;
	};

}

src/main/java/at/uda/multiplechoice/model/Teacher.java
package at.uda.multiplechoice.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

@DiscriminatorValue(value = "TEACHER")
@Entity

public class Teacher extends Person {
	@OneToMany(mappedBy = "teacher", cascade = { CascadeType.ALL }, fetch = FetchType.LAZY)
	private List<TestEntity> tests = new ArrayList<>();
	@OneToMany(mappedBy = "teacher", cascade = { CascadeType.ALL }, fetch = FetchType.LAZY)
	private List<QuestionTest> questionTests = new ArrayList<>();

	public List<TestEntity> getTests() {
		return tests;
	}

	public void setTests(List<TestEntity> tests) {
		this.tests = tests;
	}

	public List<QuestionTest> getQuestionTests() {
		return questionTests;
	}

	public void setQuestionTests(List<QuestionTest> questionTests) {
		this.questionTests = questionTests;
	}

	public void addQuestion(QuestionTest questionTest) {
		this.questionTests.add(questionTest);
		questionTest.setTeacher(this);
	}

}

src/main/java/at/uda/multiplechoice/controller/edit/EditStudentController.java
package at.uda.multiplechoice.controller.edit;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import at.uda.multiplechoice.data.StudentProducer;
import at.uda.multiplechoice.enums.Page;
import at.uda.multiplechoice.model.Student;

@SessionScoped
@Named
public class EditStudentController implements Serializable {
	private static final long serialVersionUID = 2815796004558360299L;

	@Inject
	private StudentProducer studentProducer;

	private Page lastPage;

	public String doEditStudent(Student question, String lastPage) {

		this.lastPage = Page.valueOf(lastPage);
		studentProducer.prepareEditStudent(question);
		return Page.EDIT_STUDENT.getLabel();
	}

	public String doStartStudent() {
		return Page.STUDENT_START.getLabel();
	}

	public String doAddStudent(String lastPage) {// gleich bei Orphan
		this.lastPage = Page.valueOf(lastPage);
		studentProducer.prepareAddStudent();

		return Page.ADD_STUDENT.getLabel();
	}

	public String doReadStudent(Student student, String lastPage) {
		this.lastPage = Page.valueOf(lastPage);
		studentProducer.setSelectedStudent(student);
		return Page.READ_STUDENT.getLabel();
	}

	public String doAddStudentToClassroom() {
		studentProducer.addStudentToClassroom();
		return lastPage.getLabel();
	}
	public String doEditStudentPassword(Student student, String lastPage){
		this.lastPage = Page.valueOf(lastPage);
		studentProducer.setSelectedStudent(student);
		return Page.EDIT_STUDENT_PASSWORD.getLabel();
	}
	
	
	public String doAddStudentToClassroom(Student student) {
		studentProducer.addStudentToClassroom(student);
		return "";
	}
	public String doRemoveStudentFromClassroom() {
		studentProducer.removeStudentFromClassroom();
		return lastPage.getLabel();
	}
	
	public String doRemoveStudentFromClassroom(Student student) {
		studentProducer.removeStudentFromClassroom(student);
		return "";
	}

	public String doSave() {//ident mit orphan
		studentProducer.doSave();
		return lastPage.getLabel();
	}

	public String doSaveWithoutPassword() {
		studentProducer.doSaveWithoutPassword();
		return lastPage.getLabel();
	}

	public boolean isEditMode() {
		return !studentProducer.isAddModeStudent();
	}

	public boolean isOrphan() {	
		return studentProducer.getSelectedStudent().getClassroom()==null;
	}

	public String doCancel() {
		return lastPage.getLabel();

	}

}

src/main/java/at/uda/multiplechoice/controller/list/ListExamsController.java
package at.uda.multiplechoice.controller.list;

import java.io.Serializable;
import java.util.List;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import at.uda.multiplechoice.data.list.ListExamsProducer;
import at.uda.multiplechoice.model.Exam;

@SessionScoped
@Named
public class ListExamsController implements Serializable {


	@Inject
	private ListExamsProducer listExamsProducer;

	private static final long serialVersionUID = 1L;

	public List<Exam> getAllExams() {
		return listExamsProducer.getAllExams();
	}
	public List<Exam> getStudentExams(){
		return listExamsProducer.getStudentExams();
	}
	public List<Exam> getUserStudentExams(){
		return listExamsProducer.getUserExams();
	}

	public List<Exam> getTestDateExams(){
		return listExamsProducer.getTestDateExams();
	}
	public List<Exam> getTestDateExamsArchive(){
		return listExamsProducer.getTestDateExamsArchive();
	}
	



}

src/main/java/at/uda/multiplechoice/controller/list/ListStudentsController.java
package at.uda.multiplechoice.controller.list;

import java.io.Serializable;
import java.util.List;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import at.uda.multiplechoice.data.list.ListStudentsProducer;
import at.uda.multiplechoice.model.Student;
import at.uda.multiplechoice.service.EntityService;

@SessionScoped
@Named
public class ListStudentsController implements Serializable {

	@Inject
	private ListStudentsProducer listStudentsProducer;
	@Inject 
	private EntityService entityService;

	private static final long serialVersionUID = 1L;
	


	public List<Student> getAllStudentsOrphans() {
		return listStudentsProducer.getStudentsOrphans();
	}
	
	public List<Student> getAllStudentsOrphansArchive() {
		return listStudentsProducer.getStudentsOrphansArchive();
	}

	public List<Student> getStudentsArchive() {
		return listStudentsProducer.getStudentsArchive();
	}
	public List<Student> getStudents() {
		return listStudentsProducer.getStudents();
	}

	public List<Student> getAllStudentsClassroom() {
		return listStudentsProducer.getStudentsClassroom();
	}
	public List<Student> getStudentsClassroomArchive() {
		return listStudentsProducer.getStudentsClassroomArchive();
	}
	
	public String doRemoveStudent(Student student){
		listStudentsProducer.removeStudent(student);
		return "";
	}
	
	public String doArchiveStudent(Student student) {
		entityService.archive(student);
		return "";
	}
	
	

	public String doNoArchiveStudent(Student student) {
		entityService.noArchive(student);
		return "";
	}
}

src/main/webapp/teacher/student/addStudent.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">

<h:body>
	<ui:composition template="../../public/editForm.xhtml">
		<ui:define name="form">
			<h4>#{msg['headline.addstudent']}</h4>
			<table>
				<tr>
					<td><h:commandLink 
							styleClass="btn btn-success btn-xs"
							action="#{editStudentController.doCancel()}" immediate="true"
							process="@this">
							<h:outputText value="#{msg['button.cancel']}">
							</h:outputText>
						</h:commandLink></td>
					<td class="col5"></td>
					<td><h:commandLink 
							styleClass="btn btn-success btn-xs"
							action="#{editStudentController.doSave()}">
							<b:icon name="floppy-disk"></b:icon>
							<h:outputText value="&#160;" />
							<h:outputText value="#{msg['button.save']}" />
						</h:commandLink></td>
				</tr>
			</table>
			<table>
				<tr>

					<td class="verticalalign ym-g38"><h:panelGrid width="450">
							<label>#{msg['student.firstname']}:<span
								class="color-red">*</span></label>
							<b:inputText id="firstname" value="#{selectedStudent.firstName}"
								maxlength="256" styleClass="form-control margin-bottom-20"
								size="60">
							</b:inputText>
							<h:message for="firstname" styleClass="alert-warning" />
							<label>#{msg['student.lastname']}:<span class="color-red">*</span></label>
							<b:inputText id="lastname" value="#{selectedStudent.lastName}"
								maxlength="256" styleClass="form-control margin-bottom-20">
							</b:inputText>
							<h:message for="lastname" styleClass="alert-warning" />
							<label>#{msg['student.userid']}:<span class="color-red">*</span></label>
							<b:inputText id="userid" value="#{selectedStudent.userID}"
								maxlength="256" styleClass="form-control margin-bottom-20">
							</b:inputText>
							<h:message for="userid" styleClass="alert-warning" />
							<label>#{msg['person.email']}:<span class="color-red">*</span></label>
							<b:inputText id="email" value="#{selectedStudent.emailAddress}"
								styleClass="form-control margin-bottom-20" size="60"
								placeholder="John.Doe@acme.at...">
								<f:facet name="prepend">
									<h:outputText value="@" />
								</f:facet>
								<f:validator validatorId="EmailValidator" />
							</b:inputText>
							<h:message for="email" styleClass="alert-warning" />
							<label>#{msg['person.password']}:<span class="color-red">*</span></label>
							<b:inputSecret id="password" value="#{selectedStudent.passWord}"
								match="repeated_password"
								styleClass="form-control margin-bottom-20" size="60" />
							<h:message for="password" styleClass="alert-warning" />
							<label>#{msg['person.passwordconfirm']}:<span
								class="color-red">*</span></label>
							<b:inputSecret id="repeated_password"
								value="#{selectedStudent.passWordCompare}"
								styleClass="form-control margin-bottom-20" />
							<h:message for="passwordconfirm" styleClass="alert-warning"
								size="60" />
						</h:panelGrid></td>
				</tr>
			</table>

		</ui:define>
	</ui:composition>
</h:body>



</html>

src/main/webapp/teacher/student/editStudent.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">

<h:body>
	<!-- Edit Student for teacher, no PW change -->
	<ui:composition template="../../public/editForm.xhtml">
		<ui:define name="form">
				<ui:param name="baseView" value="EDIT_STUDENT" />
			<table>
				<tr>
					<td><h:commandLink 
							styleClass="btn btn-warning btn-xs"
							action="#{editStudentController.doCancel()}" immediate="true"
							process="@this">
							<b:icon name="step-backward"></b:icon>
							<h:outputText value="&#160;" />
							<h:outputText value="#{msg['button.cancel']}">
							</h:outputText>
						</h:commandLink></td>
					<td class="col5"></td>
					<td><h:commandLink 
							styleClass="btn btn-success btn-xs"
							action="#{editStudentController.doSaveWithoutPassword()}">
							<b:icon name="floppy-disk"></b:icon>
							<h:outputText value="&#160;" />
							<h:outputText value="#{msg['button.save']}">
							</h:outputText>
						</h:commandLink></td>
					<td class="col5"></td>
				</tr>
			</table>
			<table>
				<tr>
					<td class="verticalalign ym-g38"><ui:include
							src="editStudentForm.xhtml" style="width:200px" /></td>
					<td class="verticalalign ym-g38" style="width: 520px"><ui:include
							src="editStudentView.xhtml" /></td>
				</tr>
			</table>

		</ui:define>
	</ui:composition>
</h:body>



</html>

src/main/webapp/teacher/student/editStudentView.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">

<h4>#{msg['headline.exams']}</h4>

<h:panelGrid width="450px" styleClass="verticalalign">
	<b:dataTable value="#{listExamsController.studentExams}" var="exam"
		id="studenttable" styleClass="table table-hover">
		<b:dataTableColumn styleClass="col10">
			<f:facet name="header">
				<h:outputText value="&#160;" />
			</f:facet>
			<h:commandLink  styleClass="btn btn-success btn-xs"
				action="#{editExamController.doReadExam(exam,baseView)}">
				<b:icon name="sunglasses" />
			</h:commandLink>
		</b:dataTableColumn>
		<b:dataTableColumn styleClass="col10">
			<f:facet name="header">
				<h:outputText value="&#160;" />
			</f:facet>
			<h:commandLink  styleClass="btn btn-success btn-xs"
				action="#{editExamController.doEditExam(exam,baseView)}">
				<b:icon name="edit" />
			</h:commandLink>
		</b:dataTableColumn>
		<b:dataTableColumn styleClass="col10">
			<f:facet name="header">
				<h:outputText value="&#160;" />
			</f:facet>
			<h:commandLink  styleClass="btn btn-danger btn-xs"
				action="#{editExamController.doRemoveExam(exam)}">
				<b:icon name="remove"></b:icon>
			</h:commandLink>
		</b:dataTableColumn>
		<b:dataTableColumn styleClass="col100">
			<f:facet name="header">#{msg['general.date']}</f:facet>
			<h:outputText  value="#{exam.testDate.testDate}">
				<f:convertDateTime pattern="dd.MM.yyyy" />
			</h:outputText>
		</b:dataTableColumn>

		<b:dataTableColumn styleClass="col100">
			<f:facet name="header">#{msg['general.title']}</f:facet>
			<h:outputText  value="#{exam.testDate.test.title}">
			</h:outputText>
		</b:dataTableColumn>
		<b:dataTableColumn>
			<f:facet name="header">
				<h:outputText value="Finished" />
			</f:facet>
			<h:graphicImage library="images" name="checked.png"
				rendered="#{exam.finished}" height="20" width="20" />
			<h:graphicImage library="images" name="unchecked.png"
				rendered="#{not exam.finished}" height="20" width="20" />
		</b:dataTableColumn>
		<b:dataTableColumn>
			<f:facet name="header">
				<h:outputText value="Pass" />
			</f:facet>
			<h:graphicImage library="images" name="checked.png"
				rendered="#{exam.pass}" height="20" width="20" />
			<h:graphicImage library="images" name="unchecked.png"
				rendered="#{not exam.pass}" height="20" width="20" />
		</b:dataTableColumn>
		<b:dataTableColumn>
			<f:facet name="header">
				<h:outputText value="Grade" />
			</f:facet>
			<h:outputText  value="#{exam.passGrade}" rendered="#{exam.passGrade>0}">
			</h:outputText>
		</b:dataTableColumn>
	</b:dataTable>
</h:panelGrid>


</html>

src/main/webapp/teacher/student/listStudent.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">
<h:body>
	<ui:composition template="../../public/editForm.xhtml">
		<ui:define name="form">
			<ui:param name="baseView" value="LIST_STUDENT" />
			<table>
				<tr>
					<td class="col400 verticalalign"><ui:include
							src="listStudentView.xhtml" />
					<td class="col50" />
					</td>
					<td class="col400 verticalalign"><ui:include
							src="listStudentViewArchive.xhtml" /></td>
				</tr>
			</table>
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/teacher/student/listStudentOrphanView.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">


<h4>#{msg['headline.liststudent']} #{msg['general.orphan']}</h4>
<b:dataTable value="#{listStudentsController.allStudentsOrphans}"
	var="student" styleClass="table table-hover">
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-warning btn-xs"
			action="#{listStudentsController.doArchiveStudent(student)}">
			<b:icon name="trash" />
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-success btn-xs"
			action="#{editStudentController.doEditStudent(student,baseView)}">
			<b:icon name="edit" />
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-success btn-xs"
			action="#{editStudentController.doAddStudentToClassroom(student)}">
			<b:icon name="plus" />
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col100">
		<f:facet name="header">#{msg['person.lastname']}</f:facet>
		<h:outputText value="#{student.lastName}">
		</h:outputText>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col100">
		<f:facet name="header">#{msg['person.firstname']}</f:facet>
		<h:outputText value="#{student.firstName}">
		</h:outputText>
	</b:dataTableColumn>
</b:dataTable>
</html>

src/main/webapp/teacher/student/listStudentOrphanViewArchive.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">


<h4> #{msg['general.archive']}</h4>
<b:dataTable value="#{listStudentsController.allStudentsOrphansArchive}"
	var="student" styleClass="table table-hover">
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-success btn-xs"
			action="#{listStudentsController.doNoArchiveStudent(student)}">
			<b:icon name="thumbs-up"></b:icon>
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-danger btn-xs"
			action="#{listStudentsController.doRemoveStudent(student)}">
			<b:icon name="remove"></b:icon>
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-success btn-xs"
			action="#{editStudentController.doEditStudent(student,baseView)}">
			<b:icon name="edit" />
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col100">
		<f:facet name="header">#{msg['person.lastname']}</f:facet>
		<h:outputText value="#{student.lastName}">
		</h:outputText>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col100">
		<f:facet name="header">#{msg['person.firstname']}</f:facet>
		<h:outputText value="#{student.firstName}">
		</h:outputText>
	</b:dataTableColumn>
</b:dataTable>
</html>

src/main/webapp/teacher/student/listStudentView.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">


<h4>#{msg['headline.liststudent']}</h4>
<b:dataTable value="#{listStudentsController.students}" var="student"
	styleClass="table table-hover">
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-warning btn-xs"
			action="#{listStudentsController.doArchiveStudent(student)}">
			<b:icon name="trash" />
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;"/>
		</f:facet>
		<h:commandLink  styleClass="btn btn-success btn-xs"
			action="#{editStudentController.doEditStudent(student,baseView)}">
			<b:icon name="edit" />
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-warning btn-xs"
			action="#{editStudentController.doRemoveStudentFromClassroom(student)}">
			<b:icon name="minus" />
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col100">
		<f:facet name="header">
			<h:outputText value="#{msg['person.lastname']}" styleClass="nowrap" />
		</f:facet>
		<h:outputText value="#{student.lastName}">
		</h:outputText>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col100">
		<f:facet name="header">
			<h:outputText value="#{msg['person.firstname']}" styleClass="nowrap" />
		</f:facet>
		<h:outputText value="#{student.firstName}">
		</h:outputText>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col100">
		<f:facet name="header">#{msg['headline.classroom']}</f:facet>
		<h:outputText value="#{student.classroom.classroomId}">
		</h:outputText>
	</b:dataTableColumn>
</b:dataTable>
</html>

src/main/webapp/teacher/student/listStudentViewArchive.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">
<h4>#{msg['general.archive']}</h4>
<b:dataTable value="#{listStudentsController.studentsArchive}"
	var="student" styleClass="table table-hover">
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-success btn-xs"
			action="#{listStudentsController.doNoArchiveStudent(student)}">
			<b:icon name="thumbs-up"></b:icon>
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-danger btn-xs"
			action="#{listStudentsController.doRemoveStudent(student)}">
			<b:icon name="remove"></b:icon>
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-success btn-xs"
			action="#{editStudentController.doEditStudent(student,baseView)}">
			<b:icon name="edit" />
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col100">
		<f:facet name="header">
			<h:outputText value="#{msg['person.lastname']}" styleClass="nowrap" />
		</f:facet>
		<h:outputText value="#{student.lastName}">
		</h:outputText>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col100">
		<f:facet name="header">
			<h:outputText value="#{msg['person.firstname']}" styleClass="nowrap" />
		</f:facet>
		<h:outputText value="#{student.firstName}">
		</h:outputText>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col100">
		<f:facet name="header">#{msg['headline.classroom']}</f:facet>
		<h:outputText value="#{student.classroom.classroomId}">
		</h:outputText>
	</b:dataTableColumn>
</b:dataTable>
</html>