src/main/java/at/uda/multiplechoice/model/Classroom.java
package at.uda.multiplechoice.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import at.uda.multiplechoice.util.RegexExpressions;

@NamedQueries({
	@NamedQuery(name = "Classroom.findAllClassroomIds", query = "SELECT c.classroomId FROM Classroom c WHERE c.archive=false ORDER BY c.classroomId"),
		@NamedQuery(name = "Classroom.findAll", query = "SELECT c FROM Classroom c WHERE c.archive=false ORDER BY c.classroomId"),
		@NamedQuery(name = "Classroom.findArchive", query = "SELECT c FROM Classroom c WHERE c.archive=true ORDER BY c.classroomId"),
		@NamedQuery(name="Classroom.findClassroomByClassroomId", query="SELECT c FROM Classroom c WHERE c.archive=false AND c.classroomId= :param ORDER BY c.createDate")
		})
@Entity
public class Classroom extends AbstractEntity{
	public static String findAll = "Classroom.findAll";
	public static String findAllClassroomIds = "Classroom.findAllClassroomIds";
	public static String findArchive = "Classroom.findArchive";
	public static String findClassroomByClassroomId = "Classroom.findClassroomByClassroomId";
	
	@NotNull
	@Pattern(regexp=RegexExpressions.NAME, message="{message.classroomid}")
	@Size(min=3, max=10, message="{message.char100}")
	private String classroomId;

	@OneToMany(mappedBy = "classroom", cascade = {CascadeType.ALL}, fetch=FetchType.LAZY, orphanRemoval=true)
	private List<Student> students=new ArrayList<>();
	
	

	@OneToMany(mappedBy = "classroom", cascade = {CascadeType.ALL}, fetch=FetchType.LAZY, orphanRemoval=true)
	private List<TestDate> testDates=new ArrayList<>();

	
    public void addStudent(Student student) {
        student.setClassroom(this);
        this.students.add(student);
    }
    public void addTestDate(TestDate testDate){
    	testDate.setClassroom(this);
    	this.testDates.add(testDate);
    }
    


	public String getClassroomId() {
		return classroomId;
	}

	public void setClassroomId(String classroomId) {
		this.classroomId = classroomId;
	}

	public List<Student> getStudents() {
		return students;
	}

	public void setStudents(List<Student> students) {
		this.students = students;
	}

	public List<TestDate> getTestDates() {
		return testDates;
	}

	public void setTestDates(List<TestDate> testDates) {
		this.testDates = testDates;
	}
	@Override
	public List<Student> getChildren(){
		return students;
	}

}

src/main/java/at/uda/multiplechoice/model/Teacher.java
package at.uda.multiplechoice.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

@DiscriminatorValue(value = "TEACHER")
@Entity

public class Teacher extends Person {
	@OneToMany(mappedBy = "teacher", cascade = { CascadeType.ALL }, fetch = FetchType.LAZY)
	private List<TestEntity> tests = new ArrayList<>();
	@OneToMany(mappedBy = "teacher", cascade = { CascadeType.ALL }, fetch = FetchType.LAZY)
	private List<QuestionTest> questionTests = new ArrayList<>();

	public List<TestEntity> getTests() {
		return tests;
	}

	public void setTests(List<TestEntity> tests) {
		this.tests = tests;
	}

	public List<QuestionTest> getQuestionTests() {
		return questionTests;
	}

	public void setQuestionTests(List<QuestionTest> questionTests) {
		this.questionTests = questionTests;
	}

	public void addQuestion(QuestionTest questionTest) {
		this.questionTests.add(questionTest);
		questionTest.setTeacher(this);
	}

}

src/main/java/at/uda/multiplechoice/controller/edit/EditClassroomController.java
package at.uda.multiplechoice.controller.edit;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.faces.bean.ManagedBean;
import javax.inject.Inject;
import javax.inject.Named;

import at.uda.multiplechoice.data.ClassroomProducer;
import at.uda.multiplechoice.enums.Page;
import at.uda.multiplechoice.model.Classroom;

@ManagedBean(name = "editClassroomController", eager = true)
@SessionScoped
@Named
public class EditClassroomController implements Serializable {
	private static final long serialVersionUID = 2815796004558360299L;
    @Inject
    private ClassroomProducer classroomProducer;
    
    private Page lastPage;
    

	public String doEditClassroom(Classroom classroom,String lastPage) {
		this.lastPage=Page.valueOf(lastPage);
		classroomProducer.prepareEditClassroom(classroom);
		return  Page.EDIT_CLASSROOM.getLabel();
		
	}
	
	
	public String doAddClassroom(String lastPage) {
		this.lastPage=Page.valueOf(lastPage);
		classroomProducer.prepareAddClassroom();	
		return  Page.EDIT_CLASSROOM.getLabel();
	}
	
    public String doSave() {
		 classroomProducer.doSave();
       return lastPage.getLabel();
    }

    public boolean isEditMode(){
    	return ! classroomProducer.isAddModeClassroom();
    }
    public boolean hasStudents(){
    	return classroomProducer.getSelectedClassroom().getStudents().size()>0;
    }
    
    public String doCancel() {
    	classroomProducer.doCancel();
       return lastPage.getLabel();
    }

}

src/main/java/at/uda/multiplechoice/controller/list/ListClassroomsController.java
package at.uda.multiplechoice.controller.list;

import java.io.Serializable;
import java.util.List;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import at.uda.multiplechoice.data.ClassroomProducer;
import at.uda.multiplechoice.enums.Page;
import at.uda.multiplechoice.model.Classroom;
import at.uda.multiplechoice.service.EntityService;

@SessionScoped
@Named
public class ListClassroomsController implements Serializable {

	@Inject
	private ClassroomProducer classroomProducer;
	@Inject
	private EntityService entityService;

	private static final long serialVersionUID = 1L;

	public String doArchiveClassroom(Classroom classroom) {
		entityService.archive(classroom);
		return "";
	}
	public String doNoArchiveClassroom(Classroom classroom) {
		entityService.noArchive(classroom);
		return "";
	}


	public String doReadClassroom(Classroom classroom) {
		classroomProducer.prepareEditClassroom(classroom);
		return  Page.EDIT_CLASSROOM.getLabel();
	}

	public List<Classroom> getAllClassrooms() {
		return classroomProducer.getAllClassrooms();
	}
	
	public List<Classroom> getAllArchiveClassrooms() {
		return classroomProducer.getArchiveClassrooms();
	}

	public void doRemoveClassroom(Classroom classroom) {
		entityService.remove(Classroom.class, classroom);
	}
}

src/main/webapp/teacher/classroom/editClassroom.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">



<h:body>
	<ui:composition template="../../public/editForm.xhtml">
		<ui:define name="form">
			<ui:param name="baseView" value="EDIT_CLASSROOM" />

			<table>
				<tr>
					<td><h:commandLink 
							styleClass="btn btn-success btn-xs"
							action="#{editClassroomController.doCancel()}" immediate="true"
							process="@this">
							<b:icon name="step-backward"></b:icon>
							<h:outputText value="&#160;" />
							<h:outputText value="#{msg['button.cancel']}" />
						</h:commandLink></td>
					<td class="col5"></td>
					<td><h:commandLink 
							styleClass="btn btn-success btn-xs"
							action="#{editClassroomController.doSave()}">
							<b:icon name="floppy-disk"></b:icon>
							<h:outputText value="&#160;" />
							<h:outputText value="#{msg['button.save']}" />
						</h:commandLink></td>
					<td class="col5"></td>
					<td><h:commandLink 
							styleClass="btn btn-success btn-xs"
							action="#{editStudentController.doAddStudent(baseView)}">
							<b:icon name="plus" />
							<h:outputText value="&#160;" />
							<h:outputText value="#{msg['button.addstudent']}">
							</h:outputText>
						</h:commandLink></td>
				</tr>
			</table>
			<table>
				<tr>
					<td class="col200 verticalalign"><ui:include
							src="editClassroomForm.xhtml"/></td>
					<td class="col450 verticalalign"><ui:include
							src="editClassroomView.xhtml" /></td>
					<td class="col450 verticalalign"><ui:include
							src="editClassroomViewArchive.xhtml" /></td>
				</tr>
			</table>
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/teacher/classroom/editClassroomForm.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">
<h:panelGrid width="200px">
	<h:messages globalOnly="true" styleClass="alert-warning" />
	<h4>#{msg['headline.classroom']}</h4>
	<label>#{msg['classroom.classroomid']}:<span class="color-red">*</span></label>
	<b:inputText id="classroomid" value="#{selectedClassroom.classroomId}"
		maxlength="256" styleClass="form-control margin-bottom-20">
	</b:inputText>
	<h:message for="classroomid" styleClass="alert-warning" />
</h:panelGrid>
</html>

src/main/webapp/teacher/classroom/editClassroomView.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">



<h4>#{msg['headline.students']}</h4>
<h:panelGrid width="450px" styleClass="verticalalign">
	<b:dataTable value="#{listStudentsController.allStudentsClassroom}"
		var="Student" id="studenttable" styleClass="table table-hover">
		<b:dataTableColumn styleClass="col10"> 
			<f:facet name="header"><h:outputText value="&#160;" /></f:facet>
				<h:commandLink  styleClass="btn btn-warning btn-xs"
					action="#{listStudentsController.doArchiveStudent(Student)}">
					<b:icon name="trash"></b:icon>
				</h:commandLink>
		</b:dataTableColumn>
		<b:dataTableColumn styleClass="col10"> 
			<f:facet name="header"><h:outputText value="&#160;" /></f:facet>
				<h:commandLink  styleClass="btn btn-warning btn-xs"
					action="#{editStudentController.doRemoveStudentFromClassroom(Student)}">
					<b:icon name="minus"></b:icon>
				</h:commandLink>
		</b:dataTableColumn>
		<b:dataTableColumn styleClass="col10"> 
			<f:facet name="header"><h:outputText value="&#160;" /></f:facet>
				<h:commandLink  styleClass="btn btn-success btn-xs"
					action="#{editStudentController.doEditStudent(Student,baseView)}">
					<b:icon name="edit" />
				</h:commandLink>
		</b:dataTableColumn>		
		<b:dataTableColumn styleClass="col100">
			<f:facet name="header"><h:outputText value="&#160;" /></f:facet>
				<h:commandLink  styleClass="btn btn-warning btn-xs"
					action="#{editStudentController.doEditStudentPassword(Student, baseView)}">
					<b:icon name="edit" />
					<h:outputText value="&#160;" />
					<h:outputText value="Password">
					</h:outputText>
				</h:commandLink>
		</b:dataTableColumn>
		<b:dataTableColumn styleClass="col150">
			<f:facet name="header">#{msg['person.lastname']}</f:facet>
				<h:outputText  value="#{Student.lastName}">
				</h:outputText>
		</b:dataTableColumn>
		<b:dataTableColumn styleClass="col50">
			<f:facet name="header">#{msg['person.userid']}</f:facet>
				<h:outputText  value="#{Student.userID}">
				</h:outputText>
		</b:dataTableColumn>
	</b:dataTable>
</h:panelGrid>
</html>

src/main/webapp/teacher/classroom/editClassroomViewArchive.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">

<h4>#{msg['headline.students']} #{msg['general.archive']}</h4>
<h:panelGrid width="430px" styleClass="verticalalign">
	<b:dataTable value="#{listStudentsController.studentsClassroomArchive}"
		var="student" styleClass="table table-hover">
		<b:dataTableColumn styleClass="col10">
			<f:facet name="header">
				<h:outputText value="&#160;" />
			</f:facet>
			<h:commandLink  styleClass="btn btn-success btn-xs"
				action="#{listStudentsController.doNoArchiveStudent(student)}">
				<b:icon name="thumbs-up"></b:icon>
			</h:commandLink>
		</b:dataTableColumn>
		<b:dataTableColumn styleClass="col10">
			<f:facet name="header">
				<h:outputText value="&#160;" />
			</f:facet>
			<h:commandLink  styleClass="btn btn-danger btn-xs"
				action="#{listStudentsController.doRemoveStudent(student)}">
				<b:icon name="remove"></b:icon>
			</h:commandLink>
		</b:dataTableColumn>
		<b:dataTableColumn styleClass="col10">
			<f:facet name="header">
				<h:outputText value="&#160;" />
			</f:facet>
			<h:commandLink  styleClass="btn btn-success btn-xs"
				action="#{editStudentController.doEditStudent(Student,baseView)}">
				<b:icon name="edit" />
			</h:commandLink>
		</b:dataTableColumn>
		<b:dataTableColumn>
			<f:facet name="header">#{msg['person.lastname']}</f:facet>
			<h:panelGrid width="100px">
				<h:outputText value="#{student.lastName}">
				</h:outputText>
			</h:panelGrid>
		</b:dataTableColumn>
		<b:dataTableColumn>
			<f:facet name="header">#{msg['person.userid']}</f:facet>
			<h:panelGrid width="100px">
				<h:outputText value="#{student.userID}">
				</h:outputText>
			</h:panelGrid>
		</b:dataTableColumn>
	</b:dataTable>
</h:panelGrid>
</html>

src/main/webapp/teacher/classroom/listClassroom.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">

<h:body>
	<ui:composition template="../../public/editForm.xhtml">
		<ui:define name="form">
			<ui:param name="baseView" value="LIST_CLASSROOM" />
			<div class="paddingleft0 panel-heading">
				<h3>#{msg['headline.listclassroom']}</h3>
			</div>
			<table>
				<tr>
					<td><h:commandLink 
							styleClass="btn btn-success btn-xs"
							action="#{editClassroomController.doAddClassroom(baseView)}">
							<b:icon name="plus" />
							<h:outputText value="&#160;" />
							<h:outputText value="#{msg['headline.classroom']}" />
						</h:commandLink></td>
					<td class="col5"></td>
				</tr>
				<tr>
					<td class="height20 col5"></td>
				</tr>
			</table>
			<table>
				<tr>
					<td class="col400 verticalalign" ><ui:include
							src="listClassroomView.xhtml"/>
						<td class="col50"/>	
							</td>
					<td class="col400 verticalalign">
					<ui:include
							src="listClassroomViewArchive.xhtml" /></td>
				</tr>
			</table>
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/teacher/classroom/listClassroomView.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">


<h4>#{msg['headline.listclassroom']}</h4>
<b:dataTable value="#{listClassroomsController.allClassrooms}"
	var="classroom" styleClass="table table-hover">
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-warning btn-xs"
			action="#{listClassroomsController.doArchiveClassroom(classroom)}">
			<b:icon name="trash" />
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-success btn-xs"
			action="#{editClassroomController.doEditClassroom(classroom,baseView)}">
			<b:icon name="edit" />
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col100">
		<f:facet name="header">#{msg['general.id']}</f:facet>
		<h:panelGrid width="70px">
			<h:outputText value="#{classroom.classroomId}" />
		</h:panelGrid>
	</b:dataTableColumn>
</b:dataTable>
</html>

src/main/webapp/teacher/classroom/listClassroomViewArchive.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">
<h4>#{msg['general.archive']}</h4>
<b:dataTable value="#{listClassroomsController.allArchiveClassrooms}"
	var="classroom" styleClass="table table-hover">

	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-success btn-xs"
			action="#{listClassroomsController.doNoArchiveClassroom(classroom)}">
			<b:icon name="thumbs-up"></b:icon>
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-danger btn-xs"
			action="#{listClassroomsController.doRemoveClassroom(classroom)}">
			<b:icon name="remove"></b:icon>
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-success btn-xs"
			action="#{editClassroomController.doEditClassroom(classroom,baseView)}">
			<b:icon name="edit" />
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col100">
		<f:facet name="header">#{msg['general.id']}</f:facet>
		<h:panelGrid width="70px">
			<h:outputText value="#{classroom.classroomId}" />
		</h:panelGrid>
	</b:dataTableColumn>
</b:dataTable>
</html>