src/main/java/at/uda/multiplechoice/model/Teacher.java
package at.uda.multiplechoice.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

@DiscriminatorValue(value = "TEACHER")
@Entity

public class Teacher extends Person {
	@OneToMany(mappedBy = "teacher", cascade = { CascadeType.ALL }, fetch = FetchType.LAZY)
	private List<TestEntity> tests = new ArrayList<>();
	@OneToMany(mappedBy = "teacher", cascade = { CascadeType.ALL }, fetch = FetchType.LAZY)
	private List<QuestionTest> questionTests = new ArrayList<>();

	public List<TestEntity> getTests() {
		return tests;
	}

	public void setTests(List<TestEntity> tests) {
		this.tests = tests;
	}

	public List<QuestionTest> getQuestionTests() {
		return questionTests;
	}

	public void setQuestionTests(List<QuestionTest> questionTests) {
		this.questionTests = questionTests;
	}

	public void addQuestion(QuestionTest questionTest) {
		this.questionTests.add(questionTest);
		questionTest.setTeacher(this);
	}

}

src/main/java/at/uda/multiplechoice/model/TestDate.java
package at.uda.multiplechoice.model;
//Neu Zwischen Test und Exam
//Exam für einen Student

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
@NamedQueries({
	@NamedQuery(name="TestDate.findAll", query="SELECT t FROM TestDate t WHERE t.archive=false  ORDER BY t.testDate DESC"),
	@NamedQuery(name="TestDate.findArchive", query="SELECT td FROM TestDate td JOIN td.test t WHERE td.archive=true  ORDER BY td.testDate DESC"),
	@NamedQuery(name = "TestDate.findTestDatesClassroom", query = "SELECT t FROM TestDate t JOIN t.classroom c WHERE c.id =:param AND t.archive = FALSE "),
	@NamedQuery(name = "TestDate.findTestDatesTest", query = "SELECT td FROM TestDate td JOIN td.test t WHERE t.id =:param AND td.archive = FALSE  ORDER BY td.createDate DESC"),
	@NamedQuery(name = "TestDate.findTestDatesTeacherAll", query = "SELECT td FROM TestDate td WHERE td.test.teacher.id =:param AND td.archive = FALSE  ORDER BY td.createDate DESC"),
	@NamedQuery(name = "TestDate.findTestDatesTeacherArchive", query = "SELECT td FROM TestDate td WHERE td.test.teacher.id =:param AND td.archive = TRUE  ORDER BY td.createDate DESC"),
})
@Entity
public class TestDate extends AbstractEntity {
	
	

	@ManyToOne()
	private TestEntity test;
	@ManyToOne()
	private Classroom classroom;	
	private Date testDate;
	
	private boolean simulation=false;

	public static final String findAll="TestDate.findAll";
	public static final String findArchive="TestDate.findArchive";
	public static final String findTestDatesClassroom="TestDate.findTestDatesClassroom";
	public static final String findTestDatesTest="TestDate.findTestDatesTest";
	public static final String findTestDatesTeacherAll="TestDate.findTestDatesTeacherAll";
	public static final String findTestDatesTeacherArchive="TestDate.findTestDatesTeacherArchive";
	
	@OneToMany(mappedBy="testDate",cascade = {CascadeType.ALL}, fetch=FetchType.LAZY)
	private List<Exam> exams=new ArrayList<>();
	private boolean finished=false;
	
	public void addExam(Exam exam){
		exam.setTestDate(this);
		this.exams.add(exam);
	}

	public TestEntity getTest() {
		return test;
	}

	public void setTest(TestEntity test) {
		this.test = test;
	}

	public List<Exam> getExams() {
		return exams;
	}

	public void setExams(List<Exam> exams) {
		this.exams = exams;
	}


	public Date getTestDate() {
		return testDate;
	}

	public void setTestDate(Date testDate) {
		this.testDate = testDate;
	}



	public Classroom getClassroom() {
		return classroom;
	}

	public void setClassroom(Classroom classroom) {
		this.classroom = classroom;
	}

	public boolean isFinished() {
		return finished;
	}

	public void setFinished(boolean finished) {
		this.finished = finished;
	}

	public boolean isSimulation() {
		return simulation;
	}

	public void setSimulation(boolean simulation) {
		this.simulation = simulation;
	}
	@Override
	public void removeForeignKeys() {
		this.test=null;
		this.classroom=null;
	}
	@Override
	public <T extends AbstractEntity> void setParent(T entity) {
		test = (TestEntity) entity;
	};

}

src/main/java/at/uda/multiplechoice/controller/edit/EditTestDateController.java
package at.uda.multiplechoice.controller.edit;

import java.io.Serializable;
import java.util.List;

import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import at.uda.multiplechoice.controller.ExamQuestionController;
import at.uda.multiplechoice.data.ClassroomProducer;
import at.uda.multiplechoice.data.ExamProducer;
import at.uda.multiplechoice.data.TestDateProducer;
import at.uda.multiplechoice.data.list.ListQuestionsTestProducer;
import at.uda.multiplechoice.enums.Page;
import at.uda.multiplechoice.model.Classroom;
import at.uda.multiplechoice.model.TestDate;

@ManagedBean(name = "editTestDateController", eager = true)
@SessionScoped
@Named
public class EditTestDateController implements Serializable {
	private static final long serialVersionUID = 2815796004558360299L;

	@Inject
	private TestDateProducer testDateProducer;
	@Inject
	private ExamProducer examProducer;
	@Inject
	private ClassroomProducer classroomProducer;
	@Inject 
	private ExamQuestionController examQuestionController;
	@Inject 
	private ListQuestionsTestProducer questionsProducer;
	private Page lastPage;
	private List<String> classroomIds;
	private String classroomId;

	public String doEditTestDate(TestDate testDate, String lastPage) {
		this.lastPage = Page.valueOf(lastPage);
		testDateProducer.prepareEditTestDate(testDate);
		classroomIds = testDateProducer.getClassroomIds();
		return Page.EDIT_TESTDATE.getLabel();
	}
	public String doReadTestDate(TestDate testDate, String lastPage) {
		this.lastPage = Page.valueOf(lastPage);
		testDateProducer.prepareEditTestDate(testDate);
		classroomIds = testDateProducer.getClassroomIds();
		return Page.READ_TESTDATE.getLabel();
	}


	public String doAddExamClassroom(String lastPage) {
		this.lastPage = Page.valueOf(lastPage);
		this.doSave();
		Classroom classroom = classroomProducer.getClassroomByClassroomId(this.classroomId);
		classroomProducer.setSelectedClassroom(classroom);
		examProducer.prepareAddExamClassroom(testDateProducer.getSelectedTestDate());
		return Page.LIST_TESTDATE.getLabel();
	}

	public String doAddRealExam(String lastPage) {
		
		if(!validate()) return "";		
		this.lastPage = Page.valueOf(lastPage);
		classroomIds = testDateProducer.getClassroomIds();
		testDateProducer.prepareAddTestDate();
		return Page.EDIT_TESTDATE.getLabel();
	}
	
	public String doAddExamSimulation(String lastPage) {
		if(!validate()) return "";	
		
		examProducer.prepareSimulationExam();
		return examQuestionController.startExam();
	}
	
	private boolean validate(){
		int  noOfquestions=questionsProducer.getQuestionsTest().size();
		if(noOfquestions<1 || noOfquestions>100){
			FacesContext facesContext = FacesContext.getCurrentInstance();
			FacesMessage facesMessage = new FacesMessage("Please enter the correct number of questions (1 - 100).");
			facesContext.addMessage(null, facesMessage);
			return false;
		}
		return true;
	}

	public String doAddTestDateToTest(TestDate testDate) {
		testDateProducer.addTestDateToTest(testDate);
		return "";
	}


	public String doSave() {
		testDateProducer.doSave();
		return lastPage.getLabel();
	}
	
	public String deleteTestExam(){	
		testDateProducer.remove();
		return Page.EDIT_TEST.getLabel();
	}

	public boolean isEditMode() {
		return !testDateProducer.isAddModeTestDate();
	}

	public String doCancel() {
		return lastPage.getLabel();

	}

	public List<String> getClassroomIds() {
		return classroomIds;
	}

	public void setClassroomIds(List<String> classroomIds) {
		this.classroomIds = classroomIds;
	}

	public String getClassroomId() {
		return classroomId;
	}

	public void setClassroomId(String classroomId) {
		this.classroomId = classroomId;
	}

}

src/main/java/at/uda/multiplechoice/controller/list/ListExamsController.java
package at.uda.multiplechoice.controller.list;

import java.io.Serializable;
import java.util.List;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import at.uda.multiplechoice.data.list.ListExamsProducer;
import at.uda.multiplechoice.model.Exam;

@SessionScoped
@Named
public class ListExamsController implements Serializable {


	@Inject
	private ListExamsProducer listExamsProducer;

	private static final long serialVersionUID = 1L;

	public List<Exam> getAllExams() {
		return listExamsProducer.getAllExams();
	}
	public List<Exam> getStudentExams(){
		return listExamsProducer.getStudentExams();
	}
	public List<Exam> getUserStudentExams(){
		return listExamsProducer.getUserExams();
	}

	public List<Exam> getTestDateExams(){
		return listExamsProducer.getTestDateExams();
	}
	public List<Exam> getTestDateExamsArchive(){
		return listExamsProducer.getTestDateExamsArchive();
	}
	



}

src/main/java/at/uda/multiplechoice/controller/list/ListTestDatesController.java
package at.uda.multiplechoice.controller.list;

import java.io.Serializable;
import java.util.List;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import at.uda.multiplechoice.data.list.ListTestDatesProducer;
import at.uda.multiplechoice.model.TestDate;
import at.uda.multiplechoice.service.EntityService;

@SessionScoped
@Named
public class ListTestDatesController implements Serializable {

	@Inject
	private ListTestDatesProducer listTestDatesProducer;
	@Inject
	private EntityService entityService;

	private static final long serialVersionUID = 1L;
	

	public String archive(TestDate test)  {
		entityService.archive(test);
		return "";
	}

	public String noArchive(TestDate test)  {
		entityService.noArchive(test);
		return "";
	}
	public String remove(TestDate test)  {
		entityService.remove(TestDate.class,test);
		return "";
	}

	public List<TestDate> getAllTestDatesClassroom() {
		return listTestDatesProducer.getTestDatesClassroom();
	}

	public List<TestDate> getAllTestDatesArchive() {
		return listTestDatesProducer.getTestDatesArchive();
	}

	public List<TestDate> getAllTestDate() {
		return listTestDatesProducer.getTestDatesAll();
	}


}

src/main/webapp/teacher/testdate/editTestDate.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">

<h:body>
	<ui:composition template="../../public/editForm.xhtml">
		<ui:define name="form">
			<table>
				<tr>
					<td><h:commandLink 
							styleClass="btn btn-success btn-xs"
							action="#{editTestDateController.doCancel()}" immediate="true"
							process="@this">
							<b:icon name="step-backward"></b:icon>
							<h:outputText value="&#160;" />
							<h:outputText value="#{msg['button.cancel']}" />
						</h:commandLink></td>
					<td class="col5"></td>
					<td><h:commandLink 
							styleClass="btn btn-success btn-xs"
							action="#{editTestDateController.doAddExamClassroom('EDIT_TESTDATE')}"
							rendered="#{addModeTestDate}">
							<b:icon name="plus" />
							<h:outputText value="&#160;"/>
							<h:outputText value="#{msg['button.createtestdateclassroom']}">
								</h:outputText>
						</h:commandLink></td>
					<td class="col5"></td>
				</tr>
			</table>
			<table>
				<tr>
					<td class="verticalalign col450" ><ui:include
							src="editTestDateForm.xhtml"/></td>
				</tr>

			</table>
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/teacher/testdate/editTestDateForm.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">

<h4>#{msg['headline.testdate']}</h4>
<h:panelGrid width="450px">
	<label>Classrooms:</label>
	<b:selectOneMenu value="#{editTestDateController.classroomId}"
		id="classrooms" immediate="true" styleClass="form">
		<f:selectItem itemValue="#{null}" itemLabel="--select--"
			noSelectionOption="true" itemDisabled="true" />
		<f:selectItems value="#{editTestDateController.classroomIds}"
			var="classroom" itemLabel="#{classroom}" itemValue="#{classroom}" />
	</b:selectOneMenu>

	<label>Test Date:<span class="color-red">*</span></label>

	<h:inputText value="#{selectedTestDate.testDate}" id="datepicker"
		name="datepicker"
		class="form-control form-control margin-bottom-20 bf-no-message has-success"
		maxlength="12" size="12">
		<f:convertDateTime pattern="dd.MM.yyyy" />
	</h:inputText>
	<h:message for="datepicker" styleClass="alert-warning" />
</h:panelGrid>
</html>

src/main/webapp/teacher/testdate/listTestDateClassroom.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">
<h:body>
	<ui:composition template="../../public/editForm.xhtml">
		<ui:define name="form">
			<ui:param name="baseView" value="LIST_TESTDATE_TEST" />
			<div class="paddingleft0 panel-heading">
				<h1>List Testdate Classroom</h1>
			</div>

			<table>
				<tr>
					<td class="col5"></td>
				</tr>
			</table>
			<table>
				<tr>
					<td class="verticalalign ym-g38"><h:panelGrid width="450px">
							<label>Classrooms:</label>

							<b:selectOneMenu
								value="#{dropdownClassroomController.selectedClassroom}"
								id="Classrooms" converter="#{ClassroomConverter}"
								onblur="submit()" immediate="true">
								<f:selectItem itemValue="#{null}" itemLabel="--select--"
									noSelectionOption="true" itemDisabled="true" />
								<f:selectItems
									value="#{dropdownClassroomController.allClassrooms}"
									var="Classroom" itemLabel="#{Classroom.classroomId}"
									itemValue="#{Classroom}" />
							</b:selectOneMenu>


						</h:panelGrid></td>
					<td class="col5"></td>
					<td><h:commandLink 
							styleClass="btn btn-success btn-xs"
							action="#{dropdownTestController.doSave()}">
							<h:outputText value="Set Test">
							</h:outputText>
						</h:commandLink></td>
				</tr>
			</table>
			<table>
				<tr>
					<td class="verticalalign"><b:dataTable
							value="#{listTestDatesController.allTestDatesClassroom}"
							var="testDate" styleClass="table table-hover">
							<b:dataTableColumn>
								<f:facet name="header"></f:facet>
								<h:panelGrid width="70px">
									<h:commandLink  styleClass="btn btn-warning btn-xs"
										action="#{listTestDatesController.doArchiveTestDate(testDate)}">
										<h:outputText value="Archive">
										</h:outputText>
									</h:commandLink>
								</h:panelGrid>
							</b:dataTableColumn>
							<b:dataTableColumn>
								<f:facet name="header"></f:facet>
								<h:panelGrid width="70px">
									<h:commandLink  styleClass="btn btn-warning btn-xs"
										action="#{editTestDateController.doEditTestDate(testDate,baseView)}">
										<h:outputText value="Edit">
										</h:outputText>
									</h:commandLink>
								</h:panelGrid>
							</b:dataTableColumn>
							<b:dataTableColumn>
								<f:facet name="header"></f:facet>
								<h:panelGrid width="70px">
									<h:commandLink  styleClass="btn btn-warning btn-xs"
										action="#{editTestDateController.doRemoveTestDate(testDate)}">
										<h:outputText value="Remove">
										</h:outputText>
									</h:commandLink>
								</h:panelGrid>
							</b:dataTableColumn>
							<b:dataTableColumn>
								<f:facet name="header">Create Date</f:facet>
								<h:panelGrid width="100px">
									<h:outputText value="#{testDate.createDate}">
									</h:outputText>
								</h:panelGrid>
							</b:dataTableColumn>
							<b:dataTableColumn>
								<f:facet name="header">Test Date</f:facet>
								<h:panelGrid width="100px">
									<h:outputText value="#{testDate.testDate}">
									</h:outputText>
								</h:panelGrid>
							</b:dataTableColumn>
						</b:dataTable></td>
				</tr>
			</table>
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/teacher/testdate/listTestDateView.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">
<h4>#{msg['headline.listtestdate']}</h4>
<b:dataTable value="#{listTestDatesController.allTestDate}"
	var="testDate" styleClass="table table-hover">
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-success btn-xs"
			action="#{editTestDateController.doReadTestDate(testDate,baseView)}">
			<b:icon name="sunglasses" />
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-warning btn-xs"
			action="#{listTestDatesController.archive(testDate)}">
			<b:icon name="trash" />
		</h:commandLink>
	</b:dataTableColumn>

	<b:dataTableColumn styleClass="col100">
		<f:facet name="header">#{msg['general.title']}</f:facet>
		<h:outputText value="#{testDate.test.title}">
		</h:outputText>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col100">
		<f:facet name="header">#{msg['general.testdate']}</f:facet>
		<h:outputText value="#{testDate.testDate}">
			<f:convertDateTime pattern="dd.MM.YYYY" />
		</h:outputText>
	</b:dataTableColumn>

</b:dataTable>
</html>

src/main/webapp/teacher/testdate/listTestDateViewArchive.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">
<h4>#{msg['general.archive']}</h4>
<b:dataTable value="#{listTestDatesController.allTestDatesArchive}"
	var="testDate" styleClass="table table-hover">
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-success btn-xs"
			action="#{listTestDatesController.noArchive(testDate)}">
			<b:icon name="thumbs-up"></b:icon>
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-danger btn-xs"
			action="#{listTestDatesController.remove(testDate)}">
			<b:icon name="remove"></b:icon>
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col100">
		<f:facet name="header">#{msg['general.title']}</f:facet>
		<h:outputText value="#{testDate.test.title}">
		</h:outputText>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col100">
		<f:facet name="header">#{msg['general.testdate']}</f:facet>
		<h:outputText value="#{testDate.testDate}">
			<f:convertDateTime pattern="dd.MM.YYYY" />
		</h:outputText>
	</b:dataTableColumn>
</b:dataTable>
</html>

src/main/webapp/teacher/testdate/readTestDateView.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">
<h4>#{msg['headline.exam']}</h4>
<b:dataTable value="#{listExamsController.testDateExams}" var="exam"
	rowIndexVar="rowIndex" id="questionTable"
	styleClass="table table-hover">
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink ajax="false" styleClass="btn btn-success btn-xs"
			action="#{editExamController.doReadExam(exam,baseView)}">
			<b:icon name="sunglasses" />
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink ajax="false" styleClass="btn btn-warning btn-xs"
			action="#{editExamController.archive(exam)}">
			<b:icon name="trash" />
		</h:commandLink>
	</b:dataTableColumn>
		<b:dataTableColumn styleClass="col100">
		<f:facet name="header"><h:outputText value="#{msg['person.lastname']}" styleClass="nowrap"/> </f:facet>
		<h:outputText ajax="false" value="#{exam.student.lastName}">
		</h:outputText>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col100">
		<f:facet name="header"><h:outputText value="#{msg['person.firstname']}" styleClass="nowrap"/></f:facet>
		<h:outputText ajax="false" value="#{exam.student.firstName}">
		</h:outputText>
	</b:dataTableColumn>

	<b:dataTableColumn styleClass="col20">
		<f:facet name="header">%</f:facet>
		<h:outputText ajax="false" value="#{exam.passPercent}">
			<f:convertNumber pattern="##0.00" />
		</h:outputText>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col20">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:outputText ajax="false" value="#{exam.passGrade}">
			<f:convertNumber integerOnly="true" />
		</h:outputText>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col20">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:graphicImage library="images" name="checked.png" height="20"
			width="20" rendered="#{exam.finished}" />
		<h:graphicImage library="images" name="unchecked.png" height="20"
			width="20" rendered="#{not exam.finished}" />
	</b:dataTableColumn>
</b:dataTable>
</html>

src/main/webapp/teacher/testdate/readTestDateViewArchive.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">
<h4>#{msg['general.archive']}</h4>
<b:dataTable value="#{listExamsController.testDateExamsArchive}"
	var="exam" rowIndexVar="rowIndex" id="questionTableArchive"
	styleClass="table table-hover">
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-success btn-xs"
			action="#{editExamController.noArchive(exam)}">
			<b:icon name="thumbs-up" />
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn>
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-danger btn-xs"
			action="#{editExamController.doRemoveExam(exam)}">
			<b:icon name="remove"></b:icon>
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col100">
		<f:facet name="header">
			<h:outputText value="#{msg['person.lastname']}" styleClass="nowrap" />
		</f:facet>
		<h:outputText  value="#{exam.student.lastName}">
		</h:outputText>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col100">
		<f:facet name="header">
			<h:outputText value="#{msg['person.firstname']}" styleClass="nowrap" />
		</f:facet>
		<h:outputText  value="#{exam.student.firstName}">
		</h:outputText>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col20">
				<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:graphicImage library="images" name="checked.png" height="20"
			width="20" rendered="#{exam.finished}" />
		<h:graphicImage library="images" name="unchecked.png" height="20"
			width="20" rendered="#{not exam.finished}" />
	</b:dataTableColumn>


</b:dataTable>
</html>