src/main/java/at/uda/multiplechoice/model/Question.java
package at.uda.multiplechoice.model;

import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import at.uda.multiplechoice.enums.Difficulty;
import at.uda.multiplechoice.util.RegexExpressions;
@Table(name = "Question")
@Inheritance(strategy=InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "TYPE")
@NamedQueries({ @NamedQuery(name = "Question.findAll", query = "SELECT q FROM Question q ORDER BY q.text"),
@NamedQuery(name="Question.findQuestionByTitle", query="SELECT q FROM Question q WHERE q.archive=false AND q.title= :param ORDER BY q.createDate")})
@Entity
public class Question extends AbstractEntity{
	
	public static final String findAll="Question.findAll";
	public static final String findQuestionByTitle="Question.findQuestionByTitle";
	@Column(nullable=false)
	
	@NotNull
	@Pattern(regexp=RegexExpressions.NAME, message="{message.title}")
	@Size(min=3, max=100, message="{message.char100}")
	private String title;
	
	@NotNull
	@Size( max=60000, message="{message.char60000}")
	@Column(length = 60000)
	private String text;
	
	@Column(nullable=false)
	private Difficulty difficulty=Difficulty.MEDIUM;
	@Column(nullable=false)
	private boolean correct=false;

	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public Difficulty getDifficulty() {
		return difficulty;
	}
	public void setDifficulty(Difficulty difficulty) {
		this.difficulty = difficulty;
	}
	public boolean isCorrect() {
		return correct;
	}
	public void setCorrect(boolean correct) {
		this.correct = correct;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}

	
}

src/main/java/at/uda/multiplechoice/model/Teacher.java
package at.uda.multiplechoice.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

@DiscriminatorValue(value = "TEACHER")
@Entity

public class Teacher extends Person {
	@OneToMany(mappedBy = "teacher", cascade = { CascadeType.ALL }, fetch = FetchType.LAZY)
	private List<TestEntity> tests = new ArrayList<>();
	@OneToMany(mappedBy = "teacher", cascade = { CascadeType.ALL }, fetch = FetchType.LAZY)
	private List<QuestionTest> questionTests = new ArrayList<>();

	public List<TestEntity> getTests() {
		return tests;
	}

	public void setTests(List<TestEntity> tests) {
		this.tests = tests;
	}

	public List<QuestionTest> getQuestionTests() {
		return questionTests;
	}

	public void setQuestionTests(List<QuestionTest> questionTests) {
		this.questionTests = questionTests;
	}

	public void addQuestion(QuestionTest questionTest) {
		this.questionTests.add(questionTest);
		questionTest.setTeacher(this);
	}

}

src/main/java/at/uda/multiplechoice/controller/edit/EditQuestionController.java
package at.uda.multiplechoice.controller.edit;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import at.uda.multiplechoice.controller.list.ListAnswersController;
import at.uda.multiplechoice.controller.list.ListQuestionsController;
import at.uda.multiplechoice.data.QuestionTestProducer;
import at.uda.multiplechoice.data.list.ListAnswersTestProducer;
import at.uda.multiplechoice.enums.Page;
import at.uda.multiplechoice.model.QuestionExam;
import at.uda.multiplechoice.model.QuestionTest;

@SessionScoped
@Named
public class EditQuestionController implements Serializable {
	private static final long serialVersionUID = 2815796004558360299L;

	@Inject
	private QuestionTestProducer questionProducer;
	@Inject
	private ListAnswersController listAnswersController;
	@Inject 
	private ListQuestionsController listQuestionsController;
	@Inject
	private ListAnswersTestProducer answers;

	private Page lastPage;
	

	public String doEditQuestion(QuestionTest question, String lastPage) {
		
		this.lastPage = Page.valueOf(lastPage);
		questionProducer.prepareEditQuestion(question);
		listAnswersController.init();
		return Page.EDIT_QUESTION.getLabel();
	}

	public String doAddQuestion(String lastPage) {//gleich bei Orphan
		this.lastPage = Page.valueOf(lastPage);
		questionProducer.prepareAddQuestion();
		listAnswersController.init();
		return Page.EDIT_QUESTION.getLabel();
	}
	public String doReadQuestion(QuestionTest question,String lastPage) {
		this.lastPage = Page.valueOf(lastPage);
		questionProducer.setSelectedQuestion(question);
		listAnswersController.init();
		
		return Page.READ_QUESTION.getLabel();
	}
	
	public String doReadQuestionExam(QuestionExam question,String lastPage) {
		this.lastPage = Page.valueOf(lastPage);
		questionProducer.setSelectedQuestion(question);
		listAnswersController.init();
		
		return Page.READ_QUESTION_EXAM.getLabel();
	}
	public String cancelQuestionExam(){
		return lastPage.getLabel();
	}
	
	public boolean isExamQuestion(){
		return questionProducer.isExamQuestion();
	}
	

	
	public String doSave() {
		int  noOfanswers=answers.getAnswersTest().size();
		if(noOfanswers<1 || noOfanswers>10){
			FacesContext facesContext = FacesContext.getCurrentInstance();
			FacesMessage facesMessage = new FacesMessage("Please enter the correct number of answers (1 - 10).");
			facesContext.addMessage(null, facesMessage);
			return "";
		}
		questionProducer.doSave();
		listQuestionsController.init();
		
		return lastPage.getLabel();
	}

	public String doSaveOrphan() {
		questionProducer.doSaveOrphan();
		listQuestionsController.init();
		return lastPage.getLabel();
	}
	public String doPreview(String lastPage) {
		return Page.PREVIEW_QUESTION.getLabel();
	}
	public String cancelPreview() {
		return 	Page.EDIT_QUESTION.getLabel();
	}


	public boolean isEditMode() {
		return !questionProducer.isAddModeQuestionTest();
	}

	public boolean isOrphan() {
		return lastPage.equals(Page.LIST_QUESTION_ORPHAN);
	}

	public String doCancel() {
		questionProducer.doCancel();
		listQuestionsController.init();		
		return lastPage.getLabel();


	}



}

src/main/java/at/uda/multiplechoice/controller/list/ListQuestionsController.java
package at.uda.multiplechoice.controller.list;

import java.io.Serializable;
import java.util.List;
import java.util.stream.Collectors;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import at.uda.multiplechoice.data.list.ListQuestionsTestProducer;
import at.uda.multiplechoice.model.QuestionTest;
import at.uda.multiplechoice.model.TestEntity;
import at.uda.multiplechoice.service.EntityService;

@SessionScoped
@Named
public class ListQuestionsController implements Serializable {//Nur QuestionTest

	@Inject
	private ListQuestionsTestProducer listQuestionsProducer;
	@Inject
	private EntityService entityService;
	
	

	private static final long serialVersionUID = 1L;
	private List<QuestionTest> listQuestionTest;
	private List<QuestionTest> listQuestionOrphan;
	private List<QuestionTest> listQuestion;
	
	@PostConstruct
	public void init(){
		listQuestionTest=listQuestionsProducer.getQuestionsTest();
		listQuestionOrphan=listQuestionsProducer.getQuestionsOrphans();
		listQuestion=listQuestionsProducer.getQuestions();
		
	}
	
	public String remove(QuestionTest question) {
		entityService.remove(QuestionTest.class,question);
		this.init();
		return "";
	}
	
	public String doArchiveOrphan(QuestionTest question) {
		entityService.archive(QuestionTest.class,question, listQuestionOrphan);
		this.init();
		return "";
	}

	public String doNoArchiveOrphan(QuestionTest question) {
		entityService.noArchive(QuestionTest.class,question, listQuestionOrphan);
		this.init();
		return "";
	}
	
	public String doArchiveQuestionWithTest(QuestionTest question) {
		TestEntity test=entityService.find(TestEntity.class, question.getTest().getId());
		List<QuestionTest> questions=entityService.getListByQueryParam(QuestionTest.class, QuestionTest.findQuestionsTest, test);
		QuestionTest question2=questions.stream().filter( q -> q.getId()==question.getId()).collect(Collectors.toList()).get(0);
		entityService.archive(QuestionTest.class,question2, questions);
		this.init();
		return "";
	}

	public String doNoArchiveQuestionWithTest(QuestionTest question) {
		TestEntity test=entityService.find(TestEntity.class, question.getTest().getId());
		List<QuestionTest> questions=entityService.getListByQueryParam(QuestionTest.class, QuestionTest.findArchiveTest, test);
		QuestionTest question2=questions.stream().filter( q -> q.getId()==question.getId()).collect(Collectors.toList()).get(0);
		List<QuestionTest> questionsActive=entityService.getListByQueryParam(QuestionTest.class, QuestionTest.findQuestionsTest, test);
		entityService.noArchive(QuestionTest.class,question2, questionsActive);
		this.init();
		return "";
	}
	
	

	public String doArchiveQuestion(QuestionTest question) {
		entityService.archive(QuestionTest.class,question, listQuestionTest);
		this.init();
		return "";
	}

	public String doNoArchiveQuestion(QuestionTest question) {
		entityService.noArchive(QuestionTest.class,question, listQuestionTest);
		this.init();
		return "";
	}
	

	public String doLowerOrder(QuestionTest question) {
		entityService.doLowerOrder(question,listQuestionTest);
		this.init();
		return "";
	}

	public String doHigherOrder(QuestionTest question) {
		entityService.doHigherOrder(question,listQuestionTest);
		this.init();
		return "";
	}

	public List<QuestionTest> getAllQuestionsOrphans() {
		return listQuestionOrphan;
	}
	public List<QuestionTest> getAllQuestionsOrphansArchive() {
		return listQuestionsProducer.getQuestionsOrphansArchive();
	}
	
	public List<QuestionTest> getAllQuestions() {
		return listQuestion;
	}

	public List<QuestionTest> getAllQuestionsArchive() {
		return listQuestionsProducer.getQuestionsArchive();
	}
	
	public List<QuestionTest> getQuestionsArchiveTest() {
		return listQuestionsProducer.getQuestionsArchiveTest();
	}

	public List<QuestionTest> getAllQuestionsTest() {
		return listQuestionTest;
	}
	public String doAddQuestionToTest(QuestionTest question){
		listQuestionsProducer.addQuestionToTest(question,listQuestionTest);
		this.init();
		return "";
	}
	
	public String doRemoveQuestion(QuestionTest question){
		listQuestionsProducer.removeQuestion(question);
		this.init();
		return "";
	}
	
	public String doRemoveQuestionFromTest(QuestionTest question){
		listQuestionsProducer.removeQuestionFromTest(question,listQuestionTest);
		this.init();
		return "";
	}


}

src/main/webapp/teacher/question/editQuestion.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">


<h:body>
	<ui:composition template="../../public/editForm.xhtml">
		<ui:define name="form">
			<ui:param name="baseView" value="EDIT_QUESTION" />
			<table>
				<tr>
					<td><h:commandLink 
							styleClass="btn btn-warning btn-xs"
							action="#{editQuestionController.doCancel()}" immediate="true"
							process="@this">
							<b:icon name="step-backward"></b:icon>
							<h:outputText value="&#160;" />
							<h:outputText value="#{msg['button.cancel']}" />
						</h:commandLink></td>
					<td class="col5"></td>
					<td><h:commandLink 
							styleClass="btn btn-success btn-xs"
							action="#{editQuestionController.doSave()}"
							rendered="#{not editQuestionController.orphan}">
							<b:icon name="floppy-disk"></b:icon>
							<h:outputText value="&#160;" />
							<h:outputText value="#{msg['button.save']}" />
						</h:commandLink></td>
					<td class="col5"></td>
					<td><h:commandLink 
							styleClass="btn btn-success btn-xs"
							action="#{editQuestionController.doSaveOrphan()}"
							rendered="#{editQuestionController.orphan}">
							<b:icon name="floppy-disk"></b:icon>
							<h:outputText value="&#160;" />
							<h:outputText value="#{msg['button.save']}" />
						</h:commandLink></td>
					<td class="col5"></td>
					<td><h:commandLink 
							styleClass="btn btn-success btn-xs"
							action="#{editAnswerController.doAddAnswer(baseView)}">
							<b:icon name="plus" />
							<h:outputText value="&#160;" />
							<h:outputText value="#{msg['headline.answer']}" />
						</h:commandLink></td>
					<td class="col5"></td>
					<td><h:commandLink 
							styleClass="btn btn-success btn-xs"
							action="#{editQuestionController.doPreview(baseView)}">
							<b:icon name="plus" />
							<h:outputText value="&#160;" />
							<h:outputText value="#{msg['general.preview']}" />
						</h:commandLink></td>
				</tr>
			</table>
			<table>
				<tr>
					<td class="col400 verticalalign ym-g38"><ui:include
							src="editQuestionForm.xhtml" /></td>
					<td class="col50" />
					<td class="col400 verticalalign ym-g38"><ui:include
							src="editQuestionView.xhtml" /></td>
					<td class="col50" />
					<td class="col400 verticalalign ym-g38"><ui:include
							src="editQuestionViewArchive.xhtml" /></td>
				</tr>
			</table>
		</ui:define>

	</ui:composition>
</h:body>
</html>

src/main/webapp/teacher/question/editQuestionForm.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui" xmlns:a4j="http://richfaces.org/a4j">
<script>
tinymce.init({
  selector: '[id$=mytextarea]',
  height: 350,
  theme: 'modern',
  plugins: [
    'advlist autolink lists link image charmap print preview hr anchor pagebreak',
    'searchreplace wordcount visualblocks visualchars code fullscreen',
    'insertdatetime media nonbreaking save table contextmenu directionality',
    'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc'
  ],
  toolbar1: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
  toolbar2: 'print preview media | forecolor backcolor emoticons | codesample',
  image_advtab: true,
  templates: [
    { title: 'Test template 1', content: 'Test 1' },
    { title: 'Test template 2', content: 'Test 2' }
  ],
  content_css: [
    '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
    '//www.tinymce.com/css/codepen.min.css'
  ]
 });
 </script>
<h4>#{msg['headline.question']}</h4>
<h:panelGrid styleClass="col400">
	<h:messages globalOnly="true" styleClass="alert-warning" />
	<label>#{msg['general.title']}:<span class="color-red">*</span></label>
	<b:inputText id="title" value="#{selectedQuestionTest.title}"
		maxlength="256" styleClass="form-control margin-bottom-20">
		<f:passThroughAttribute name="placeholder"
			value="#{msg['general.title']}" />
	</b:inputText>
	<h:message for="title" styleClass="alert-warning" />

	<label>#{msg['general.text']}:</label>
	<h:inputTextarea value="#{selectedQuestionTest.text}" id="mytextarea" />
	<h:message for="mytextarea" styleClass="alert-warning" />
</h:panelGrid>
<h:panelGrid styleClass="col200" columns="3">
	<h:outputLabel styleClass="nowrap">#{msg['general.created']}:</h:outputLabel>
	<h:outputLabel styleClass="col5"></h:outputLabel>
	<h:outputLabel styleClass="nowrap" id="createDate"
		value="#{selectedQuestionTest.createDate}">
		<f:convertDateTime pattern="dd.MM.YYYY hh:mm" />
	</h:outputLabel>
	<h:outputLabel styleClass="nowrap">#{msg['general.lastmodified']}:</h:outputLabel>
	<h:outputLabel styleClass="col5"></h:outputLabel>
	<h:outputLabel styleClass="nowrap" id="lastModified"
		value="#{selectedQuestionTest.lastModified}">
		<f:convertDateTime pattern="dd.MM.YYYY hh:mm" />
	</h:outputLabel>
</h:panelGrid>

</html>

src/main/webapp/teacher/question/listQuestions.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">
<h:body>
	<ui:composition template="../../public/editForm.xhtml">
		<ui:define name="form">
			<ui:param name="baseView" value="LIST_QUESTION" />
			<table>
				<tr>
					<td class="col400 verticalalign"><ui:include
							src="listQuestionsView.xhtml" />
					<td class="col50" />
					</td>
					<td class="col400 verticalalign"><ui:include
							src="listQuestionsViewArchive.xhtml" /></td>
				</tr>
			</table>
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/teacher/question/listQuestionsOrphansView.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">


<h4>#{msg['headline.question']} #{msg['general.orphan']}</h4>
<h:panelGrid styleClass="col400">
	<b:dataTable value="#{listQuestionsController.allQuestionsOrphans}"
		var="question" styleClass="table table-hover">

		<b:dataTableColumn styleClass="col10">
			<f:facet name="header">
				<h:outputText value="&#160;" />
			</f:facet>
			<h:commandLink  styleClass="btn btn-warning btn-xs"
				action="#{listQuestionsController.doArchiveOrphan(question)}">
				<b:icon name="trash" />
			</h:commandLink>
		</b:dataTableColumn>

		<b:dataTableColumn styleClass="col10">
			<f:facet name="header">
				<h:outputText value="&#160;" />
			</f:facet>
			<h:commandLink  styleClass="btn btn-success btn-xs"
				action="#{editQuestionController.doEditQuestion(question,baseView)}">
				<b:icon name="edit" />
			</h:commandLink>
		</b:dataTableColumn>

		<b:dataTableColumn styleClass="col10">
			<f:facet name="header">
				<h:outputText value="&#160;" />
			</f:facet>
			<h:commandLink  styleClass="btn btn-success btn-xs"
				action="#{listQuestionsController.doAddQuestionToTest(question)}">
				<b:icon name="plus" />
			</h:commandLink>
		</b:dataTableColumn>
		<b:dataTableColumn styleClass="col150">
			<f:facet name="header">#{msg['general.title']}</f:facet>
			<h:outputText value="#{question.title}">
			</h:outputText>
		</b:dataTableColumn>
	</b:dataTable>
</h:panelGrid>
</html>

src/main/webapp/teacher/question/listQuestionsOrphansViewArchive.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">


<h4>#{msg['general.archive']}</h4>
<h:panelGrid styleClass="col400">
	<b:dataTable
		value="#{listQuestionsController.allQuestionsOrphansArchive}"
		var="question" styleClass="table table-hover">
		<b:dataTableColumn styleClass="col10">
			<f:facet name="header">
				<h:outputText value="&#160;" />
			</f:facet>
			<h:commandLink  styleClass="btn btn-success btn-xs"
				action="#{listQuestionsController.doNoArchiveOrphan(question)}">
				<b:icon name="thumbs-up"></b:icon>
			</h:commandLink>
		</b:dataTableColumn>
		<b:dataTableColumn styleClass="col10">
			<f:facet name="header">
				<h:outputText value="&#160;" />
			</f:facet>
			<h:commandLink  styleClass="btn btn-danger btn-xs"
				action="#{listQuestionsController.doRemoveQuestion(question)}">
				<b:icon name="remove"></b:icon>
			</h:commandLink>
		</b:dataTableColumn>

		<b:dataTableColumn styleClass="col10">
			<f:facet name="header">
				<h:outputText value="&#160;" />
			</f:facet>
			<h:commandLink  styleClass="btn btn-success btn-xs"
				action="#{editQuestionController.doEditQuestion(question,baseView)}">
				<b:icon name="edit" />
			</h:commandLink>
		</b:dataTableColumn>

		<b:dataTableColumn styleClass="col150">
			<f:facet name="header">#{msg['general.title']}</f:facet>
			<h:outputText value="#{question.title}">
			</h:outputText>
		</b:dataTableColumn>
	</b:dataTable>
</h:panelGrid>
</html>

src/main/webapp/teacher/question/listQuestionsView.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">
<h4>#{msg['headline.question']}</h4>
<b:dataTable value="#{listQuestionsController.allQuestions}"
	var="question" styleClass="table table-hover">

	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-warning btn-xs"
			action="#{listQuestionsController.doArchiveQuestionWithTest(question)}">
			<b:icon name="trash"></b:icon>
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-success btn-xs"
			action="#{editQuestionController.doEditQuestion(question,baseView)}">
			<b:icon name="edit" />
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col100">
		<f:facet name="header">#{msg['general.title']}</f:facet>
		<h:outputText value="#{question.title}">
		</h:outputText>

	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col100">
		<f:facet name="header">#{msg['general.test']}</f:facet>
		<h:outputText value="#{question.test.title}">
		</h:outputText>
	</b:dataTableColumn>
</b:dataTable>
</html>

src/main/webapp/teacher/question/listQuestionsViewArchive.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:b="http://bootsfaces.net/ui">
<h4>#{msg['headline.question']}</h4>
<b:dataTable value="#{listQuestionsController.allQuestionsArchive}"
	var="question" styleClass="table table-hover">

	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-success btn-xs"
			action="#{listQuestionsController.doNoArchiveQuestionWithTest(question)}">
			<b:icon name="thumbs-up"></b:icon>
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-danger btn-xs"
			action="#{listQuestionsController.doRemoveQuestion(question)}">
			<b:icon name="remove"></b:icon>
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col10">
		<f:facet name="header">
			<h:outputText value="&#160;" />
		</f:facet>
		<h:commandLink  styleClass="btn btn-success btn-xs"
			action="#{editQuestionController.doEditQuestion(question,baseView)}">
			<b:icon name="edit" />
		</h:commandLink>
	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col100">
		<f:facet name="header">#{msg['general.title']}</f:facet>
		<h:outputText value="#{question.title}">
		</h:outputText>

	</b:dataTableColumn>
	<b:dataTableColumn styleClass="col100">
		<f:facet name="header">#{msg['general.test']}</f:facet>
		<h:outputText value="#{question.test.title}">
		</h:outputText>
	</b:dataTableColumn>
</b:dataTable>
</html>

src/main/webapp/teacher/question/readQuestionPreview.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
		xmlns:b="http://bootsfaces.net/ui">
	
<h:body>
	<ui:composition template="../../public/editForm.xhtml">
		<ui:define name="form">
			<table>
				<tr>
					<td><h:commandLink 
							styleClass="btn btn-warning btn-xs"
							action="#{editQuestionController.cancelPreview()}" immediate="true"
							process="@this">
							<b:icon name="step-backward"></b:icon>
							<h:outputText value="&#160;" />
							<h:outputText value="#{msg['button.cancel']}" />
						</h:commandLink></td>
					<td class="col5"></td>
				</tr>
			</table>
						<table>

				<tr>
					<td class="verticalalign ym-g38"><ui:include
							src="readQuestionPreviewForm.xhtml" style="width:480px" /></td>
				</tr>
			</table>
		</ui:define>

	</ui:composition>
</h:body>
</html>